/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BookForm.java
 *
 * Created on Jan 11, 2013, 3:18:47 PM
 */



/**
 *
 * @author root
 */
public class BookForm extends javax.swing.JPanel {

	/**
	 *
	 */
	private static final long serialVersionUID = 4990065792710352430L;

	/** Creates new form BookForm */
	public BookForm() {

		initComponents();
		setSize(241, 164);
		// setPreferredSize(new Dimension(241,164));
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify
	 * this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		this.jPanel1 = new javax.swing.JPanel();
		this.jLabel1 = new javax.swing.JLabel();
		this.jLabel2 = new javax.swing.JLabel();
		this.jTextField1 = new javax.swing.JTextField();
		this.jTextField2 = new javax.swing.JTextField();
		this.jButton1 = new javax.swing.JButton();

		setBorder(null);

		this.jLabel1.setText("Emp Name : ");

		this.jLabel2.setText("Emp Age :");

		this.jTextField1.addActionListener(evt -> jTextField1ActionPerformed(evt));

		this.jTextField2.addActionListener(evt -> jTextField2ActionPerformed(evt));

		this.jButton1.setText("Search");

		final javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
			this.jPanel1);
		this.jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(this.jLabel1)
								.addComponent(this.jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(this.jTextField2)
								.addComponent(this.jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 95,
										Short.MAX_VALUE))
						.addGap(27, 27, 27))
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(72, 72, 72)
						.addComponent(this.jButton1)
						.addContainerGap(113, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(30, 30, 30)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(this.jLabel1)
								.addComponent(this.jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(this.jLabel2)
								.addComponent(this.jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(29, 29, 29)
						.addComponent(this.jButton1)
						.addContainerGap(14, Short.MAX_VALUE)));

		final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
			this);
		setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(this.jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(this.jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField2ActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed

		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField2ActionPerformed

	private void jTextField1ActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed

		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton		jButton1;
	private javax.swing.JLabel		jLabel1;
	private javax.swing.JLabel		jLabel2;
	private javax.swing.JPanel		jPanel1;
	private javax.swing.JTextField	jTextField1;
	private javax.swing.JTextField	jTextField2;
	// End of variables declaration//GEN-END:variables

	public static void main(final String s[]) {

		final BookForm bookForm = new BookForm();
		System.out.println(bookForm.getPreferredSize());
		System.out.println(bookForm.getBounds());
	}
}
